[package]
name = "juniper_demo"
version = "0.1.0"
authors = ["Ivan Porto Carrero <ivan@oneconcern.com>"]

[dependencies]
dotenv = "0.9.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.0", features = ["postgres"] }
r2d2-diesel = "1.0"
r2d2 = "0.8"
juniper = "0.9.2"
juniper_rocket = "0.1.2"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
